---

- name: Set up checkin server
  hosts: checkin
  remote_user: root
  vars:
    server_user: checkinserver
    home_dir: /srv/checkin
    repository_url: https://github.com/SKAPfhs1920/Checkin.git
    repository_path: '{{ home_dir }}/repo'
    virtualenv_path: '{{ home_dir }}/venv'
    domain: 'checkin-server.local'
    uwsgi_socket: '{{ home_dir }}/uwsgi.sock'

  tasks:
  - name: Create server user
    user:
      name: '{{ server_user }}'
      comment: 'Checkin server'
      home: '{{ home_dir }}'
      create_home: yes
      uid: 2001

  - name: Install software
    apt: update_cache=yes name={{ item }} state=present
    with_items:
    - git
    - nginx
    - python3-pip
    - virtualenv
    - supervisor
    - uwsgi

  - name: Clone repos
    become_user: '{{ server_user }}'
    git: repo='{{ repository_url }}' dest='{{ repository_path }}'

  - name: Install requirements
    become_user: '{{ server_user }}'
    pip: requirements='{{ repository_path }}/requirements.txt' virtualenv='{{ virtualenv_path }}' virtualenv_python='python3'

  - name: Make sure nginx is running
    service: name=nginx enabled=yes state=started

  - name: Make sure supervisord is running
    service: name=supervisor enabled=yes state=started

  - name: Make sure static file path exists
    file: path={{ home_dir }}/static state=directory

  - name: Install nginx vhost confing
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/conf.d/{{ domain }}.conf
    notify: reload nginx

  - name: Install supervisor config
    template: src=templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ domain }}_uwsgi.conf mode=755
    notify: reload uwsgi

  - name: Install uwsgi config
    template: src=templates/uwsgi.yml.j2 dest={{ home_dir }}/uwsgi.yml

  - name: Start uwsgi server
    supervisorctl: name={{ domain }}_uwsgi state=restarted

  handlers:
  - name: reload nginx
    service: name=nginx state=reloaded

  - name: reload uwsgi
    supervisorctl: name={{ domain }}_uwsgi state=reread
