---

- name: Set up checkin server
  hosts: checkin
  remote_user: root
  vars:
    server_user: checkinserver
    home_dir: /srv/checkin
    repository_url: https://github.com/SKAPfhs1920/Checkin.git
    repository_path: '{{ home_dir }}/repo'
    virtualenv_path: '{{ home_dir }}/venv'
  tasks:
  - name: Create server user
    user:
      name: '{{ server_user }}'
      comment: 'Checkin server'
      home: '{{ home_dir }}'
      create_home: yes
      uid: 2001

  - name: Install software
    apt: update_cache=yes name={{ item }} state=present
    with_items:
    - git
    - nginx
    - python3-pip
    - virtualenv

  - name: Clone repos
    become_user: '{{ server_user }}'
    git: repo='{{ repository_url }}' dest='{{ repository_path }}'

  - name: Install requirements
    become_user: '{{ server_user }}'
    pip: requirements='{{ repository_path }}/requirements.txt' virtualenv='{{ virtualenv_path }}' virtualenv_python='python3'
